### ISSUE TITLE
 greendao:3.2.2  @ToOne 

### ISSUE THREAD

**Issue by longtaoge** [LeiHolmes/GreenDaoDemo#1]
greendao:3.2.2  @ToOne  的写法与 Demo 中好象不同了 

有 Room 和  RoomType 两个类 
如果这样写 
    @ToOne(joinProperty = "RoomTypeId")
    private  RoomType roomType;

Error:Execution failed for task ':app:greendao'.
> Can't find RoomTypeId in Room for @ToOne relation

**Comment by LeiHolmes** [comment]
抱歉才看到，我去验证一下

**Comment by longtaoge** [comment]
好像是我理解错了！
